"""board_prompt_items

Revision ID: 5317c6923aeb
Revises: 973f17a3f51f
Create Date: 2026-08-07 00:27:07.015810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5317c6923aeb'
down_revision: Union[str, Sequence[str], None] = '973f17a3f51f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_items', sa.Column('prompt_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board_items', 'prompt_text')
    # ### end Alembic commands ###
