"""comment_replies

Revision ID: 6d707bb04494
Revises: c0fad20be8e7
Create Date: 2026-08-09 17:03:21.741151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d707bb04494'
down_revision: Union[str, Sequence[str], None] = 'c0fad20be8e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_comments', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'board_comments', 'board_comments', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'board_comments', type_='foreignkey')
    op.drop_column('board_comments', 'parent_id')
    # ### end Alembic commands ###
