"""optional_category_english_name

Revision ID: 6e6a85cad2fe
Revises: 5317c6923aeb
Create Date: 2026-08-09 15:45:05.319252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e6a85cad2fe'
down_revision: Union[str, Sequence[str], None] = '5317c6923aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'name_en',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'name_en',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
