"""knowledge_graph

Revision ID: 973f17a3f51f
Revises: f0cb45d02a17
Create Date: 2026-08-06 21:26:36.169701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '973f17a3f51f'
down_revision: Union[str, Sequence[str], None] = 'f0cb45d02a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('normalized', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), server_default='other', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('person','organization','location','regulation','date','other')", name='ck_graph_entities_kind'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized')
    )
    op.create_index('ix_graph_entities_normalized', 'graph_entities', ['normalized'], unique=False)
    op.create_table('graph_mentions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('municipality_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('visibility', sa.Text(), nullable=False),
    sa.CheckConstraint("visibility IN ('global','municipality','department')", name='ck_graph_mentions_visibility'),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['graph_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_graph_mentions_chunk', 'graph_mentions', ['chunk_id'], unique=False)
    op.create_index('ix_graph_mentions_entity', 'graph_mentions', ['entity_id'], unique=False)
    op.create_table('graph_relations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('predicate', sa.Text(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('municipality_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('visibility', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("visibility IN ('global','municipality','department')", name='ck_graph_relations_visibility'),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['object_id'], ['graph_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['graph_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_graph_relations_chunk', 'graph_relations', ['chunk_id'], unique=False)
    op.create_index('ix_graph_relations_object', 'graph_relations', ['object_id'], unique=False)
    op.create_index('ix_graph_relations_subject', 'graph_relations', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_graph_relations_subject', table_name='graph_relations')
    op.drop_index('ix_graph_relations_object', table_name='graph_relations')
    op.drop_index('ix_graph_relations_chunk', table_name='graph_relations')
    op.drop_table('graph_relations')
    op.drop_index('ix_graph_mentions_entity', table_name='graph_mentions')
    op.drop_index('ix_graph_mentions_chunk', table_name='graph_mentions')
    op.drop_table('graph_mentions')
    op.drop_index('ix_graph_entities_normalized', table_name='graph_entities')
    op.drop_table('graph_entities')
    # ### end Alembic commands ###
