"""metrics_crons

Revision ID: ef71c9799785
Revises: da8d1c3511ef
Create Date: 2026-08-05 18:00:46.694546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef71c9799785'
down_revision: Union[str, Sequence[str], None] = 'da8d1c3511ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cron_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job', sa.Text(), nullable=False),
    sa.Column('period_key', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_cron_runs_period', 'cron_runs', ['job', 'period_key'], unique=True)
    op.create_table('daily_metrics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('municipality_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('active_users', sa.Integer(), server_default='0', nullable=False),
    sa.Column('chat_sessions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('chat_messages', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unanswered', sa.Integer(), server_default='0', nullable=False),
    sa.Column('board_items', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comments', sa.Integer(), server_default='0', nullable=False),
    sa.Column('likes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('files_uploaded', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_daily_metrics_scope', 'daily_metrics', ['day', 'municipality_id', 'department_id'], unique=True, postgresql_nulls_not_distinct=True)
    op.create_table('user_logins',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('municipality_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_logins_day', 'user_logins', ['created_at', 'municipality_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_logins_day', table_name='user_logins')
    op.drop_table('user_logins')
    op.drop_index('uq_daily_metrics_scope', table_name='daily_metrics', postgresql_nulls_not_distinct=True)
    op.drop_table('daily_metrics')
    op.drop_index('uq_cron_runs_period', table_name='cron_runs')
    op.drop_table('cron_runs')
    # ### end Alembic commands ###
