"""hybrid_search

Revision ID: f0cb45d02a17
Revises: ef71c9799785
Create Date: 2026-08-06 17:42:21.929141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0cb45d02a17'
down_revision: Union[str, Sequence[str], None] = 'ef71c9799785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('search', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', content)", persisted=True), nullable=True))
    op.create_index('ix_chunks_search', 'chunks', ['search'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunks_search', table_name='chunks', postgresql_using='gin')
    op.drop_column('chunks', 'search')
    # ### end Alembic commands ###
